name: Publish

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Publish to GitHub Packages
      env:
        THEHUB_USERNAME: ${{ github.actor }}
        THEHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew publish
